//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ht1.webservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="administrator.contact.1.0.0", Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", ConfigurationName="webservice.administratorcontact100")]
    public interface administratorcontact100 {
        
        // CODEGEN: El parámetro 'list' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="readList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="list")]
        ht1.webservice.readListResponse readList(ht1.webservice.readListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="readList", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.readListResponse> readListAsync(ht1.webservice.readListRequest request);
        
        // CODEGEN: El parámetro 'item' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="readItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="item")]
        ht1.webservice.readItemResponse readItem(ht1.webservice.readItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="readItem", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.readItemResponse> readItemAsync(ht1.webservice.readItemRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.createResponse create(ht1.webservice.createRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="create", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.createResponse> createAsync(ht1.webservice.createRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.updateResponse update(ht1.webservice.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="update", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.updateResponse> updateAsync(ht1.webservice.updateRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.deleteResponse delete(ht1.webservice.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.deleteResponse> deleteAsync(ht1.webservice.deleteRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="task_featured", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.task_featuredResponse task_featured(ht1.webservice.task_featuredRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_featured", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.task_featuredResponse> task_featuredAsync(ht1.webservice.task_featuredRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="task_unfeatured", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.task_unfeaturedResponse task_unfeatured(ht1.webservice.task_unfeaturedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_unfeatured", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.task_unfeaturedResponse> task_unfeaturedAsync(ht1.webservice.task_unfeaturedRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="task_publish", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.task_publishResponse task_publish(ht1.webservice.task_publishRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_publish", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.task_publishResponse> task_publishAsync(ht1.webservice.task_publishRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="task_unpublish", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.task_unpublishResponse task_unpublish(ht1.webservice.task_unpublishRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_unpublish", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.task_unpublishResponse> task_unpublishAsync(ht1.webservice.task_unpublishRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="task_checkin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.task_checkinResponse task_checkin(ht1.webservice.task_checkinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_checkin", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.task_checkinResponse> task_checkinAsync(ht1.webservice.task_checkinRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="task_checkout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.task_checkoutResponse task_checkout(ht1.webservice.task_checkoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_checkout", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.task_checkoutResponse> task_checkoutAsync(ht1.webservice.task_checkoutRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="task_save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.task_saveResponse task_save(ht1.webservice.task_saveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_save", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.task_saveResponse> task_saveAsync(ht1.webservice.task_saveRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="task_apply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.task_applyResponse task_apply(ht1.webservice.task_applyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_apply", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.task_applyResponse> task_applyAsync(ht1.webservice.task_applyRequest request);
        
        // CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="task_delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ht1.webservice.task_deleteResponse task_delete(ht1.webservice.task_deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ht1.webservice.task_deleteResponse> task_deleteAsync(ht1.webservice.task_deleteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl")]
    public partial class readList_filters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int publishedField;
        
        private bool publishedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int published {
            get {
                return this.publishedField;
            }
            set {
                this.publishedField = value;
                this.RaisePropertyChanged("published");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publishedSpecified {
            get {
                return this.publishedFieldSpecified;
            }
            set {
                this.publishedFieldSpecified = value;
                this.RaisePropertyChanged("publishedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl")]
    public partial class readItemResponse_item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string aliasField;
        
        private string con_positionField;
        
        private string addressField;
        
        private string suburbField;
        
        private string stateField;
        
        private string countryField;
        
        private string postcodeField;
        
        private string telephoneField;
        
        private string faxField;
        
        private string miscField;
        
        private string imageField;
        
        private string email_toField;
        
        private int default_conField;
        
        private int publishedField;
        
        private int checked_outField;
        
        private System.DateTime checked_out_timeField;
        
        private int orderingField;
        
        private string paramsField;
        
        private int user_idField;
        
        private int catidField;
        
        private int accessField;
        
        private string mobileField;
        
        private string webpageField;
        
        private string sortname1Field;
        
        private string sortname2Field;
        
        private string sortname3Field;
        
        private string languageField;
        
        private System.DateTime createdField;
        
        private int created_byField;
        
        private System.DateTime modifiedField;
        
        private int modified_byField;
        
        private string metakeyField;
        
        private string metadescField;
        
        private string metadataField;
        
        private int featuredField;
        
        private System.DateTime publish_upField;
        
        private System.DateTime publish_downField;
        
        private string versionField;
        
        private int hitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string con_position {
            get {
                return this.con_positionField;
            }
            set {
                this.con_positionField = value;
                this.RaisePropertyChanged("con_position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string suburb {
            get {
                return this.suburbField;
            }
            set {
                this.suburbField = value;
                this.RaisePropertyChanged("suburb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
                this.RaisePropertyChanged("telephone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string misc {
            get {
                return this.miscField;
            }
            set {
                this.miscField = value;
                this.RaisePropertyChanged("misc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string email_to {
            get {
                return this.email_toField;
            }
            set {
                this.email_toField = value;
                this.RaisePropertyChanged("email_to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int default_con {
            get {
                return this.default_conField;
            }
            set {
                this.default_conField = value;
                this.RaisePropertyChanged("default_con");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int published {
            get {
                return this.publishedField;
            }
            set {
                this.publishedField = value;
                this.RaisePropertyChanged("published");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int checked_out {
            get {
                return this.checked_outField;
            }
            set {
                this.checked_outField = value;
                this.RaisePropertyChanged("checked_out");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public System.DateTime checked_out_time {
            get {
                return this.checked_out_timeField;
            }
            set {
                this.checked_out_timeField = value;
                this.RaisePropertyChanged("checked_out_time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int ordering {
            get {
                return this.orderingField;
            }
            set {
                this.orderingField = value;
                this.RaisePropertyChanged("ordering");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int catid {
            get {
                return this.catidField;
            }
            set {
                this.catidField = value;
                this.RaisePropertyChanged("catid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
                this.RaisePropertyChanged("access");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string webpage {
            get {
                return this.webpageField;
            }
            set {
                this.webpageField = value;
                this.RaisePropertyChanged("webpage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string sortname1 {
            get {
                return this.sortname1Field;
            }
            set {
                this.sortname1Field = value;
                this.RaisePropertyChanged("sortname1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string sortname2 {
            get {
                return this.sortname2Field;
            }
            set {
                this.sortname2Field = value;
                this.RaisePropertyChanged("sortname2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string sortname3 {
            get {
                return this.sortname3Field;
            }
            set {
                this.sortname3Field = value;
                this.RaisePropertyChanged("sortname3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public int created_by {
            get {
                return this.created_byField;
            }
            set {
                this.created_byField = value;
                this.RaisePropertyChanged("created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public System.DateTime modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
                this.RaisePropertyChanged("modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public int modified_by {
            get {
                return this.modified_byField;
            }
            set {
                this.modified_byField = value;
                this.RaisePropertyChanged("modified_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string metakey {
            get {
                return this.metakeyField;
            }
            set {
                this.metakeyField = value;
                this.RaisePropertyChanged("metakey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string metadesc {
            get {
                return this.metadescField;
            }
            set {
                this.metadescField = value;
                this.RaisePropertyChanged("metadesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public int featured {
            get {
                return this.featuredField;
            }
            set {
                this.featuredField = value;
                this.RaisePropertyChanged("featured");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public System.DateTime publish_up {
            get {
                return this.publish_upField;
            }
            set {
                this.publish_upField = value;
                this.RaisePropertyChanged("publish_up");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public System.DateTime publish_down {
            get {
                return this.publish_downField;
            }
            set {
                this.publish_downField = value;
                this.RaisePropertyChanged("publish_down");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public int hits {
            get {
                return this.hitsField;
            }
            set {
                this.hitsField = value;
                this.RaisePropertyChanged("hits");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl")]
    public partial class readListResponse_list_item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int accessField;
        
        private int featuredField;
        
        private string languageField;
        
        private string nameField;
        
        private int orderingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
                this.RaisePropertyChanged("access");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int featured {
            get {
                return this.featuredField;
            }
            set {
                this.featuredField = value;
                this.RaisePropertyChanged("featured");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int ordering {
            get {
                return this.orderingField;
            }
            set {
                this.orderingField = value;
                this.RaisePropertyChanged("ordering");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readList", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class readListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limitStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filterSearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ht1.webservice.readList_filters filters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordering;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderingDirection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        public readListRequest() {
        }
        
        public readListRequest(int limitStart, int limit, string filterSearch, ht1.webservice.readList_filters filters, string ordering, string orderingDirection, string language) {
            this.limitStart = limitStart;
            this.limit = limit;
            this.filterSearch = filterSearch;
            this.filters = filters;
            this.ordering = ordering;
            this.orderingDirection = orderingDirection;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readListResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class readListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ht1.webservice.readListResponse_list_item[] list;
        
        public readListResponse() {
        }
        
        public readListResponse(ht1.webservice.readListResponse_list_item[] list) {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readItem", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class readItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        public readItemRequest() {
        }
        
        public readItemRequest(int id, string language) {
            this.id = id;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readItemResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class readItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ht1.webservice.readItemResponse_item item;
        
        public readItemResponse() {
        }
        
        public readItemResponse(ht1.webservice.readItemResponse_item item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class createRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int catid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int published;
        
        public createRequest() {
        }
        
        public createRequest(string name, int catid, string language, int published) {
            this.name = name;
            this.catid = catid;
            this.language = language;
            this.published = published;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public createResponse() {
        }
        
        public createResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int catid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int published;
        
        public updateRequest() {
        }
        
        public updateRequest(int id, string name, int catid, string language, int published) {
            this.id = id;
            this.name = name;
            this.catid = catid;
            this.language = language;
            this.published = published;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public updateResponse() {
        }
        
        public updateResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public deleteRequest() {
        }
        
        public deleteRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_featured", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_featuredRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_featuredRequest() {
        }
        
        public task_featuredRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_featuredResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_featuredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_featuredResponse() {
        }
        
        public task_featuredResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_unfeatured", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_unfeaturedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_unfeaturedRequest() {
        }
        
        public task_unfeaturedRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_unfeaturedResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_unfeaturedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_unfeaturedResponse() {
        }
        
        public task_unfeaturedResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_publish", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_publishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_publishRequest() {
        }
        
        public task_publishRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_publishResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_publishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_publishResponse() {
        }
        
        public task_publishResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_unpublish", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_unpublishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_unpublishRequest() {
        }
        
        public task_unpublishRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_unpublishResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_unpublishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_unpublishResponse() {
        }
        
        public task_unpublishResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_checkin", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_checkinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_checkinRequest() {
        }
        
        public task_checkinRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_checkinResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_checkinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_checkinResponse() {
        }
        
        public task_checkinResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_checkout", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_checkoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_checkoutRequest() {
        }
        
        public task_checkoutRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_checkoutResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_checkoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_checkoutResponse() {
        }
        
        public task_checkoutResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_save", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_saveRequest {
        
        public task_saveRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_saveResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_saveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_saveResponse() {
        }
        
        public task_saveResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_apply", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_applyRequest {
        
        public task_applyRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_applyResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_applyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_applyResponse() {
        }
        
        public task_applyResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_delete", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_deleteRequest {
        
        public task_deleteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_deleteResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_deleteResponse() {
        }
        
        public task_deleteResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface administratorcontact100Channel : ht1.webservice.administratorcontact100, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class administratorcontact100Client : System.ServiceModel.ClientBase<ht1.webservice.administratorcontact100>, ht1.webservice.administratorcontact100 {
        
        public administratorcontact100Client() {
        }
        
        public administratorcontact100Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public administratorcontact100Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public administratorcontact100Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public administratorcontact100Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.readListResponse ht1.webservice.administratorcontact100.readList(ht1.webservice.readListRequest request) {
            return base.Channel.readList(request);
        }
        
        public ht1.webservice.readListResponse_list_item[] readList(int limitStart, int limit, string filterSearch, ht1.webservice.readList_filters filters, string ordering, string orderingDirection, string language) {
            ht1.webservice.readListRequest inValue = new ht1.webservice.readListRequest();
            inValue.limitStart = limitStart;
            inValue.limit = limit;
            inValue.filterSearch = filterSearch;
            inValue.filters = filters;
            inValue.ordering = ordering;
            inValue.orderingDirection = orderingDirection;
            inValue.language = language;
            ht1.webservice.readListResponse retVal = ((ht1.webservice.administratorcontact100)(this)).readList(inValue);
            return retVal.list;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.readListResponse> ht1.webservice.administratorcontact100.readListAsync(ht1.webservice.readListRequest request) {
            return base.Channel.readListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.readListResponse> readListAsync(int limitStart, int limit, string filterSearch, ht1.webservice.readList_filters filters, string ordering, string orderingDirection, string language) {
            ht1.webservice.readListRequest inValue = new ht1.webservice.readListRequest();
            inValue.limitStart = limitStart;
            inValue.limit = limit;
            inValue.filterSearch = filterSearch;
            inValue.filters = filters;
            inValue.ordering = ordering;
            inValue.orderingDirection = orderingDirection;
            inValue.language = language;
            return ((ht1.webservice.administratorcontact100)(this)).readListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.readItemResponse ht1.webservice.administratorcontact100.readItem(ht1.webservice.readItemRequest request) {
            return base.Channel.readItem(request);
        }
        
        public ht1.webservice.readItemResponse_item readItem(int id, string language) {
            ht1.webservice.readItemRequest inValue = new ht1.webservice.readItemRequest();
            inValue.id = id;
            inValue.language = language;
            ht1.webservice.readItemResponse retVal = ((ht1.webservice.administratorcontact100)(this)).readItem(inValue);
            return retVal.item;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.readItemResponse> ht1.webservice.administratorcontact100.readItemAsync(ht1.webservice.readItemRequest request) {
            return base.Channel.readItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.readItemResponse> readItemAsync(int id, string language) {
            ht1.webservice.readItemRequest inValue = new ht1.webservice.readItemRequest();
            inValue.id = id;
            inValue.language = language;
            return ((ht1.webservice.administratorcontact100)(this)).readItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.createResponse ht1.webservice.administratorcontact100.create(ht1.webservice.createRequest request) {
            return base.Channel.create(request);
        }
        
        public bool create(string name, int catid, string language, int published) {
            ht1.webservice.createRequest inValue = new ht1.webservice.createRequest();
            inValue.name = name;
            inValue.catid = catid;
            inValue.language = language;
            inValue.published = published;
            ht1.webservice.createResponse retVal = ((ht1.webservice.administratorcontact100)(this)).create(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.createResponse> ht1.webservice.administratorcontact100.createAsync(ht1.webservice.createRequest request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.createResponse> createAsync(string name, int catid, string language, int published) {
            ht1.webservice.createRequest inValue = new ht1.webservice.createRequest();
            inValue.name = name;
            inValue.catid = catid;
            inValue.language = language;
            inValue.published = published;
            return ((ht1.webservice.administratorcontact100)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.updateResponse ht1.webservice.administratorcontact100.update(ht1.webservice.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(int id, string name, int catid, string language, int published) {
            ht1.webservice.updateRequest inValue = new ht1.webservice.updateRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.catid = catid;
            inValue.language = language;
            inValue.published = published;
            ht1.webservice.updateResponse retVal = ((ht1.webservice.administratorcontact100)(this)).update(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.updateResponse> ht1.webservice.administratorcontact100.updateAsync(ht1.webservice.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.updateResponse> updateAsync(int id, string name, int catid, string language, int published) {
            ht1.webservice.updateRequest inValue = new ht1.webservice.updateRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.catid = catid;
            inValue.language = language;
            inValue.published = published;
            return ((ht1.webservice.administratorcontact100)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.deleteResponse ht1.webservice.administratorcontact100.delete(ht1.webservice.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(int id) {
            ht1.webservice.deleteRequest inValue = new ht1.webservice.deleteRequest();
            inValue.id = id;
            ht1.webservice.deleteResponse retVal = ((ht1.webservice.administratorcontact100)(this)).delete(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.deleteResponse> ht1.webservice.administratorcontact100.deleteAsync(ht1.webservice.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.deleteResponse> deleteAsync(int id) {
            ht1.webservice.deleteRequest inValue = new ht1.webservice.deleteRequest();
            inValue.id = id;
            return ((ht1.webservice.administratorcontact100)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.task_featuredResponse ht1.webservice.administratorcontact100.task_featured(ht1.webservice.task_featuredRequest request) {
            return base.Channel.task_featured(request);
        }
        
        public bool task_featured(int id) {
            ht1.webservice.task_featuredRequest inValue = new ht1.webservice.task_featuredRequest();
            inValue.id = id;
            ht1.webservice.task_featuredResponse retVal = ((ht1.webservice.administratorcontact100)(this)).task_featured(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.task_featuredResponse> ht1.webservice.administratorcontact100.task_featuredAsync(ht1.webservice.task_featuredRequest request) {
            return base.Channel.task_featuredAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.task_featuredResponse> task_featuredAsync(int id) {
            ht1.webservice.task_featuredRequest inValue = new ht1.webservice.task_featuredRequest();
            inValue.id = id;
            return ((ht1.webservice.administratorcontact100)(this)).task_featuredAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.task_unfeaturedResponse ht1.webservice.administratorcontact100.task_unfeatured(ht1.webservice.task_unfeaturedRequest request) {
            return base.Channel.task_unfeatured(request);
        }
        
        public bool task_unfeatured(int id) {
            ht1.webservice.task_unfeaturedRequest inValue = new ht1.webservice.task_unfeaturedRequest();
            inValue.id = id;
            ht1.webservice.task_unfeaturedResponse retVal = ((ht1.webservice.administratorcontact100)(this)).task_unfeatured(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.task_unfeaturedResponse> ht1.webservice.administratorcontact100.task_unfeaturedAsync(ht1.webservice.task_unfeaturedRequest request) {
            return base.Channel.task_unfeaturedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.task_unfeaturedResponse> task_unfeaturedAsync(int id) {
            ht1.webservice.task_unfeaturedRequest inValue = new ht1.webservice.task_unfeaturedRequest();
            inValue.id = id;
            return ((ht1.webservice.administratorcontact100)(this)).task_unfeaturedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.task_publishResponse ht1.webservice.administratorcontact100.task_publish(ht1.webservice.task_publishRequest request) {
            return base.Channel.task_publish(request);
        }
        
        public bool task_publish(int id) {
            ht1.webservice.task_publishRequest inValue = new ht1.webservice.task_publishRequest();
            inValue.id = id;
            ht1.webservice.task_publishResponse retVal = ((ht1.webservice.administratorcontact100)(this)).task_publish(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.task_publishResponse> ht1.webservice.administratorcontact100.task_publishAsync(ht1.webservice.task_publishRequest request) {
            return base.Channel.task_publishAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.task_publishResponse> task_publishAsync(int id) {
            ht1.webservice.task_publishRequest inValue = new ht1.webservice.task_publishRequest();
            inValue.id = id;
            return ((ht1.webservice.administratorcontact100)(this)).task_publishAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.task_unpublishResponse ht1.webservice.administratorcontact100.task_unpublish(ht1.webservice.task_unpublishRequest request) {
            return base.Channel.task_unpublish(request);
        }
        
        public bool task_unpublish(int id) {
            ht1.webservice.task_unpublishRequest inValue = new ht1.webservice.task_unpublishRequest();
            inValue.id = id;
            ht1.webservice.task_unpublishResponse retVal = ((ht1.webservice.administratorcontact100)(this)).task_unpublish(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.task_unpublishResponse> ht1.webservice.administratorcontact100.task_unpublishAsync(ht1.webservice.task_unpublishRequest request) {
            return base.Channel.task_unpublishAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.task_unpublishResponse> task_unpublishAsync(int id) {
            ht1.webservice.task_unpublishRequest inValue = new ht1.webservice.task_unpublishRequest();
            inValue.id = id;
            return ((ht1.webservice.administratorcontact100)(this)).task_unpublishAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.task_checkinResponse ht1.webservice.administratorcontact100.task_checkin(ht1.webservice.task_checkinRequest request) {
            return base.Channel.task_checkin(request);
        }
        
        public bool task_checkin(int id) {
            ht1.webservice.task_checkinRequest inValue = new ht1.webservice.task_checkinRequest();
            inValue.id = id;
            ht1.webservice.task_checkinResponse retVal = ((ht1.webservice.administratorcontact100)(this)).task_checkin(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.task_checkinResponse> ht1.webservice.administratorcontact100.task_checkinAsync(ht1.webservice.task_checkinRequest request) {
            return base.Channel.task_checkinAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.task_checkinResponse> task_checkinAsync(int id) {
            ht1.webservice.task_checkinRequest inValue = new ht1.webservice.task_checkinRequest();
            inValue.id = id;
            return ((ht1.webservice.administratorcontact100)(this)).task_checkinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.task_checkoutResponse ht1.webservice.administratorcontact100.task_checkout(ht1.webservice.task_checkoutRequest request) {
            return base.Channel.task_checkout(request);
        }
        
        public bool task_checkout(int id) {
            ht1.webservice.task_checkoutRequest inValue = new ht1.webservice.task_checkoutRequest();
            inValue.id = id;
            ht1.webservice.task_checkoutResponse retVal = ((ht1.webservice.administratorcontact100)(this)).task_checkout(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.task_checkoutResponse> ht1.webservice.administratorcontact100.task_checkoutAsync(ht1.webservice.task_checkoutRequest request) {
            return base.Channel.task_checkoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.task_checkoutResponse> task_checkoutAsync(int id) {
            ht1.webservice.task_checkoutRequest inValue = new ht1.webservice.task_checkoutRequest();
            inValue.id = id;
            return ((ht1.webservice.administratorcontact100)(this)).task_checkoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.task_saveResponse ht1.webservice.administratorcontact100.task_save(ht1.webservice.task_saveRequest request) {
            return base.Channel.task_save(request);
        }
        
        public bool task_save() {
            ht1.webservice.task_saveRequest inValue = new ht1.webservice.task_saveRequest();
            ht1.webservice.task_saveResponse retVal = ((ht1.webservice.administratorcontact100)(this)).task_save(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.task_saveResponse> ht1.webservice.administratorcontact100.task_saveAsync(ht1.webservice.task_saveRequest request) {
            return base.Channel.task_saveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.task_saveResponse> task_saveAsync() {
            ht1.webservice.task_saveRequest inValue = new ht1.webservice.task_saveRequest();
            return ((ht1.webservice.administratorcontact100)(this)).task_saveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.task_applyResponse ht1.webservice.administratorcontact100.task_apply(ht1.webservice.task_applyRequest request) {
            return base.Channel.task_apply(request);
        }
        
        public bool task_apply() {
            ht1.webservice.task_applyRequest inValue = new ht1.webservice.task_applyRequest();
            ht1.webservice.task_applyResponse retVal = ((ht1.webservice.administratorcontact100)(this)).task_apply(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.task_applyResponse> ht1.webservice.administratorcontact100.task_applyAsync(ht1.webservice.task_applyRequest request) {
            return base.Channel.task_applyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.task_applyResponse> task_applyAsync() {
            ht1.webservice.task_applyRequest inValue = new ht1.webservice.task_applyRequest();
            return ((ht1.webservice.administratorcontact100)(this)).task_applyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ht1.webservice.task_deleteResponse ht1.webservice.administratorcontact100.task_delete(ht1.webservice.task_deleteRequest request) {
            return base.Channel.task_delete(request);
        }
        
        public bool task_delete() {
            ht1.webservice.task_deleteRequest inValue = new ht1.webservice.task_deleteRequest();
            ht1.webservice.task_deleteResponse retVal = ((ht1.webservice.administratorcontact100)(this)).task_delete(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ht1.webservice.task_deleteResponse> ht1.webservice.administratorcontact100.task_deleteAsync(ht1.webservice.task_deleteRequest request) {
            return base.Channel.task_deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ht1.webservice.task_deleteResponse> task_deleteAsync() {
            ht1.webservice.task_deleteRequest inValue = new ht1.webservice.task_deleteRequest();
            return ((ht1.webservice.administratorcontact100)(this)).task_deleteAsync(inValue);
        }

        internal string readListAsync()
        {
            throw new NotImplementedException();
        }
    }
}
